# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22)),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
