# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Listen',
        ),
        migrations.RenameField(
            model_name='listen',
            old_name='spotify_id',
            new_name='song_spotify_id',
        ),
    ]
