# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0002_auto_20161106_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_id', models.CharField(max_length=25)),
                ('access_token', models.CharField(max_length=260)),
                ('scope', models.CharField(max_length=260)),
                ('refresh_token', models.CharField(max_length=64)),
                ('access_token_expiration', models.DateTimeField()),
            ],
        ),
    ]
