# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listen',
            old_name='listened_at',
            new_name='start',
        ),
        migrations.AddField(
            model_name='listen',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
