# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0005_auto_20161107_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_token',
            new_name='fitbit_access_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='access_token_expiration',
            new_name='fitbit_access_token_expiration',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='refresh_token',
            new_name='fitbit_refresh_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='scope',
            new_name='fitbit_scope',
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_access_token_expiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_scope',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
