# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0007_auto_20161116_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=260)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfitbit.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfitbit.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='sfitbit.Artist'),
        ),
        migrations.AddField(
            model_name='listen',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfitbit.Track'),
        ),
    ]
