# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0009_auto_20161116_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='tempo',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
