# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0010_track_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='average_heart_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
