# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0012_auto_20161117_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('time', models.IntegerField()),
                ('listen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfitbit.Listen')),
            ],
        ),
    ]
