# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0015_auto_20161123_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenaudiosegment',
            name='hr_loudness_correlation',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='listenaudiosegment',
            name='hr_tempo_correlation',
            field=models.DecimalField(decimal_places=7, max_digits=12, null=True),
        ),
    ]
