# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0016_auto_20161123_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosegment',
            name='is_accurate',
            field=models.IntegerField(null=True),
        ),
    ]
