# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0017_audiosegment_is_accurate'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartrate',
            name='z_score',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
