# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0019_auto_20161126_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='z_score',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True),
        ),
    ]
