# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfitbit', '0020_auto_20161126_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='z_score',
            field=models.DecimalField(decimal_places=14, max_digits=16, null=True),
        ),
    ]
